name: dino
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2025.4.26=hbd8a1cb_0
  - ld_impl_linux-64=2.43=h712a8e2_4
  - libexpat=2.7.0=h5888daf_0
  - libffi=3.4.6=h2dba641_1
  - libgcc=15.1.0=h767d61c_2
  - libgcc-ng=15.1.0=h69a702a_2
  - libgomp=15.1.0=h767d61c_2
  - liblzma=5.8.1=hb9d3cd8_1
  - libnsl=2.0.1=hd590300_0
  - libsqlite=3.49.2=hee588c1_0
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.5.0=h7b32b05_1
  - pip=25.1.1=pyh8b19718_0
  - python=3.10.17=hd6af730_0_cpython
  - readline=8.2=h8c095d6_2
  - setuptools=80.8.0=pyhff2d567_0
  - tk=8.6.13=noxft_h4845f30_101
  - wheel=0.45.1=pyhd8ed1ab_1
  - pip:
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.9.0
      - cachetools==5.5.2
      - certifi==2025.4.26
      - clip==0.2.0
      - decorator==5.2.1
      - distro==1.9.0
      - fsspec==2025.5.1
      - ftfy==6.3.1
      - google-ai-generativelanguage==0.6.15
      - google-api-core==2.25.0rc1
      - google-api-python-client==2.170.0
      - google-auth==2.40.2
      - google-auth-httplib2==0.2.0
      - google-generativeai==0.8.5
      - googleapis-common-protos==1.70.0
      - groundingdino==0.1.0
      - grpcio==1.71.0
      - grpcio-status==1.71.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httplib2==0.22.0
      - httpx==0.28.1
      - huggingface-hub==0.32.1
      - hydra-core==1.3.2
      - idna==3.10
      - iopath==0.1.10
      - ipdb==0.13.13
      - jinja2==3.1.6
      - jiter==0.10.0
      - markupsafe==3.0.2
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - omegaconf==2.3.0
      - open-clip-torch==2.32.0
      - openai==1.82.1
      - packaging==25.0
      - pandas==2.2.3
      - pexpect==4.9.0
      - pillow==11.3.0
      - portalocker==3.1.1
      - proto-plus==1.26.1
      - protobuf==5.29.5
      - ptyprocess==0.7.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.11.5
      - pydantic-core==2.33.2
      - pygments==2.19.1
      - pyparsing==3.2.3
      - pytz==2025.2
      - rsa==4.9.1
      - sam-2==1.0
      - six==1.17.0
      - sniffio==1.3.1
      - supervision==0.25.1
      - sympy==1.13.1
      - timm==1.0.15
      - tokenizers==0.21.1
      - torch==2.5.1
      - torchvision==0.20.1
      - transformers==4.52.3
      - triton==3.1.0
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - uritemplate==4.1.1
      - urllib3==2.4.0
prefix: ./yourpath/conda_env/envs/dino
