name: crab
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2025.1.31=hbcca054_0
  - ld_impl_linux-64=2.43=h712a8e2_4
  - libffi=3.4.6=h2dba641_0
  - libgcc=14.2.0=h767d61c_2
  - libgcc-ng=14.2.0=h69a702a_2
  - libgomp=14.2.0=h767d61c_2
  - liblzma=5.6.4=hb9d3cd8_0
  - libnsl=2.0.1=hd590300_0
  - libsqlite=3.49.1=hee588c1_2
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.4.1=h7b32b05_0
  - python=3.9.21=h9c0c6dc_1_cpython
  - readline=8.2=h8c095d6_2
  - tk=8.6.13=noxft_h4845f30_101
  - pip:
      - absl-py==2.1.0
      - accelerate==0.33.0
      - aiohappyeyeballs==2.3.4
      - aiohttp==3.10.0
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - anyio==2.2.0
      - argon2-cffi==20.1.0
      - asttokens==3.0.0
      - async-generator==1.10
      - async-timeout==4.0.3
      - attrs==20.3.0
      - audioread==3.0.1
      - av==14.4.0
      - babel==2.9.0
      - backcall==0.2.0
      - backports-tarfile==1.2.0
      - bitsandbytes==0.45.3
      - bleach==3.3.0
      - cachetools==5.5.0
      - certifi==2020.12.5
      - cffi==1.14.5
      - chardet==4.0.0
      - charset-normalizer==3.3.2
      - click==8.1.8
      - cmake==3.30.5
      - contourpy==1.2.1
      - cryptography==45.0.4
      - cycler==0.12.1
      - datasets==2.20.0
      - decorator==4.4.2
      - decord==0.6.0
      - deepspeed==0.12.6
      - defusedxml==0.7.1
      - deprecation==2.1.0
      - dill==0.3.8
      - dnspython==2.7.0
      - docker-pycreds==0.4.0
      - docutils==0.21.2
      - einops==0.8.0
      - entrypoints==0.3
      - et-xmlfile==2.0.0
      - eval-type-backport==0.2.2
      - exceptiongroup==1.2.2
      - executing==2.2.0
      - filelock==3.15.4
      - fonttools==4.53.1
      - frozenlist==1.4.1
      - fsspec==2024.5.0
      - ftfy==6.2.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - grpcio==1.68.1
      - h11==0.14.0
      - hf-xet==1.1.5
      - hjson==3.1.0
      - httpcore==1.0.7
      - httplib2==0.22.0
      - httpx==0.28.1
      - huggingface-hub==0.33.2
      - id==1.5.0
      - idna==2.10
      - imageio==2.35.0
      - imageio-ffmpeg==0.5.1
      - importlib-metadata==8.2.0
      - importlib-resources==6.4.0
      - iopath==0.1.10
      - ipdb==0.13.13
      - ipykernel==5.5.3
      - ipython==7.22.0
      - ipython-genutils==0.2.0
      - jaraco-classes==3.4.0
      - jaraco-context==6.0.1
      - jaraco-functools==4.1.0
      - jedi==0.18.0
      - jeepney==0.9.0
      - jinja2==3.1.4
      - joblib==1.4.2
      - json5==0.9.5
      - jsonlines==4.0.0
      - jsonschema==3.2.0
      - jupyter-client==6.2.0
      - jupyter-core==4.7.1
      - jupyter-packaging==0.9.1
      - jupyter-server==1.6.1
      - jupyterlab==3.0.14
      - jupyterlab-pygments==0.1.2
      - jupyterlab-server==2.4.0
      - keyring==25.6.0
      - kiwisolver==1.4.5
      - lazy-loader==0.4
      - librosa==0.10.2.post1
      - lit==18.1.8
      - llvmlite==0.43.0
      - lxml==6.0.0
      - markdown==3.6
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.9.1
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mistune==0.8.4
      - more-itertools==10.7.0
      - moviepy==1.0.3
      - mpmath==1.3.0
      - msgpack==1.0.8
      - multidict==6.0.5
      - multiprocess==0.70.16
      - nbclassic==0.2.7
      - nbclient==0.5.3
      - nbconvert==6.0.7
      - nbformat==5.1.3
      - nest-asyncio==1.5.1
      - networkx==3.2.1
      - nh3==0.2.21
      - ninja==1.11.1.1
      - notebook==6.3.0
      - numba==0.60.0
      - numpy==1.26.4
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cublas-cu12==12.4.2.65
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-cupti-cu12==12.4.99
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-nvrtc-cu12==12.4.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cuda-runtime-cu12==12.4.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.2.0.44
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-curand-cu12==10.3.5.119
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusolver-cu12==11.6.0.99
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-cusparse-cu12==12.3.0.142
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-ml-py==12.555.43
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.4.99
      - nvidia-nvtx-cu11==11.7.91
      - nvidia-nvtx-cu12==12.4.99
      - opencv-python==4.10.0.84
      - openpyxl==3.1.5
      - packaging==25.0
      - pandas==2.2.2
      - pandocfilters==1.4.3
      - parso==0.8.2
      - peft==0.12.0
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==10.4.0
      - pip==25.1.1
      - platformdirs==4.2.2
      - pooch==1.8.2
      - portalocker==2.10.1
      - proglog==0.1.10
      - prometheus-client==0.10.1
      - prompt-toolkit==3.0.18
      - protobuf==4.25.3
      - psutil==6.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pyarrow==17.0.0
      - pyarrow-hotfix==0.6
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pycparser==2.20
      - pycrawlers==1.1.6
      - pydantic==2.8.2
      - pydantic-core==2.20.1
      - pydub==0.25.1
      - pygments==2.19.1
      - pyjwt==2.8.0
      - pymongo==4.13.2
      - pynvml==11.5.3
      - pyparsing==2.4.7
      - pyrsistent==0.17.3
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.1
      - pyzmq==22.0.3
      - qwen-omni-utils==0.0.8
      - readme-renderer==44.0
      - regex==2024.7.24
      - requests==2.32.3
      - requests-toolbelt==1.0.0
      - rfc3986==2.0.0
      - rich==14.0.0
      - rsa==4.9
      - safetensors==0.4.3
      - scikit-learn==1.5.1
      - scipy==1.13.1
      - seaborn==0.13.2
      - secretstorage==3.3.3
      - send2trash==1.5.0
      - sentencepiece==0.2.0
      - sentry-sdk==2.29.1
      - setproctitle==1.3.6
      - setuptools==75.1.0
      - six==1.15.0
      - smmap==5.0.2
      - sniffio==1.2.0
      - soundfile==0.12.1
      - soxr==0.4.0
      - stack-data==0.6.3
      - sympy==1.13.3
      - tabulate==0.9.0
      - tenacity==9.1.2
      - tensorboard==2.17.0
      - tensorboard-data-server==0.7.2
      - terminado==0.9.4
      - testpath==0.4.4
      - thop==0.1.1-2209072238
      - threadpoolctl==3.5.0
      - tiktoken==0.7.0
      - timm==1.0.8
      - tokenizers==0.15.2
      - tomli==2.2.1
      - tomlkit==0.7.0
      - torch==2.4.0+cu124
      - torchaudio==2.4.0+cu124
      - torchvision==0.19.0+cu124
      - tornado==6.1
      - towhee==1.1.3
      - towhee-models==1.1.3
      - tqdm==4.66.4
      - traitlets==5.0.5
      - transformers==4.37.2
      - transformers-stream-generator==0.0.5
      - triton==3.0.0
      - twine==6.1.0
      - typing-extensions==4.12.2
      - tzdata==2024.1
      - uritemplate==4.1.1
      - urllib3==2.4.0
      - wandb==0.19.11
      - wcwidth==0.2.13
      - webencodings==0.5.1
      - werkzeug==3.0.1
      - wheel==0.36.2
      - xxhash==3.4.1
      - yarl==1.9.4
      - zhipuai==2.1.5.20241204
      - zipp==3.19.2
prefix: yourpath/conda_env/envs/think
